# Generated by Django 5.1.11 on 2025-08-19 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('vendor', models.CharField(blank=True, max_length=255)),
                ('pdf', models.FileField(upload_to='agreements/')),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('term_months', models.PositiveIntegerField(default=12)),
                ('notice_days', models.PositiveIntegerField(default=90)),
                ('auto_renews', models.BooleanField(default=True)),
                ('renewal_text', models.TextField(blank=True)),
                ('parsed_fields', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
